do_train=False
do_predict=True
vocab_file='./BIOBERT_DIR/vocab.txt'
bert_config_file='./BIOBERT_DIR/bert_config.json'
init_checkpoint='https://drive.google.com/open?id=1wqH8eovuqQGi3C81YDgSmWnn5UcHkWYQ/biobert_model.ckpt'
max_seq_length=384
train_batch_size=12
learning_rate=5e-6
doc_stride=128
num_train_epochs=5.0
do_lower_case=False
predict_file='./BIOASQ_DIR/Question.json'
output_dir='./tmp/QA_output/'
max_query_length = 64
predict_batch_size = 8
warmup_proportion = 0.1
save_checkpoints_steps = 1000
iterations_per_loop = 1000
n_best_size = 20
max_answer_length = 30
use_tpu = False
tpu_name = None
tpu_zone = None
gcp_project = None
master = None
num_tpu_cores = 8
verbose_logging = False
version_2_with_negative = False
null_score_diff_threshold = 0.0